// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IBlogPostFields {
  /** Post ID */
  postId: string;

  /** Title */
  title?: string | undefined;

  /** Publish Date */
  publishDate?: string | undefined;

  /** Topic Tags */
  topicTags?: string[] | undefined;

  /** Hero Banner */
  heroBanner?: Asset | undefined;

  /** Body */
  body?: Document | undefined;
}

/** Individual blog post */

export interface IBlogPost extends Entry<IBlogPostFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "blogPost";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ICodeSnippetFields {
  /** Code */
  code: string;

  /** Language */
  language:
    | "python"
    | "java"
    | "javascript"
    | "c"
    | "cpp"
    | "jsx"
    | "json"
    | "markdown"
    | "graphql"
    | "sql"
    | "powershell"
    | "typescript"
    | "tsx"
    | "regex"
    | "docker"
    | "dot"
    | "css"
    | "csharp"
    | "objectivec"
    | "cmake"
    | "django"
    | "swift";

  /** Blog Post */
  postId: IBlogPost;
}

/** Code snippet with metadata for rich text */

export interface ICodeSnippet extends Entry<ICodeSnippetFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "codeSnippet";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ILanguageFields {
  /** Name */
  name: string;

  /** Image */
  img: Asset;

  /** Accent Color */
  accentColor: string;

  /** Dark Text? */
  darkText: boolean;
}

/** Programming language profile */

export interface ILanguage extends Entry<ILanguageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "language";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ILanguageGroupFields {
  /** Heading */
  heading: string;

  /** Description */
  description: string;

  /** Emoji */
  emoji: string;

  /** Emoji Label */
  emojiLabel: string;

  /** Order */
  order: number;

  /** Languages */
  languages: ILanguage[];
}

/** Group of programming languages */

export interface ILanguageGroup extends Entry<ILanguageGroupFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "languageGroup";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IResumeBubblesSectionFields {
  /** Heading */
  heading: string;

  /** Order */
  order: number;

  /** Items */
  items: string[];
}

/** Section of events styled as bubbles */

export interface IResumeBubblesSection extends Entry<IResumeBubblesSectionFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "resumeBubblesSection";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IResumeTabSectionFields {
  /** Heading */
  heading: string;

  /** Subsections */
  subsections: Entry<{ [fieldId: string]: unknown }>[];

  /** Order */
  order: number;
}

/** Section of events styled under tabs */

export interface IResumeTabSection extends Entry<IResumeTabSectionFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "resumeTabSection";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IResumeTabSubsectionFields {
  /** Title */
  title: string;

  /** Organization */
  organization: string;

  /** Start Date */
  startDate: string;

  /** End Date */
  endDate?: string | undefined;

  /** Currently Working? */
  currentlyWorking: boolean;

  /** Description */
  description: Document;
}

/** Subsection of specific event for resume tab section */

export interface IResumeTabSubsection extends Entry<IResumeTabSubsectionFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "resumeTabSubsection";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ITimelineEventFields {
  /** Heading */
  heading: string;

  /** Type */
  type: "Internship" | "Education" | "Work";

  /** Start Date */
  startDate: string;

  /** End Date */
  endDate?: string | undefined;

  /** Currently Working? */
  currentlyWorking: boolean;

  /** Description */
  description: Document;
}

/** Event for home screen timeline */

export interface ITimelineEvent extends Entry<ITimelineEventFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "timelineEvent";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE =
  | "blogPost"
  | "codeSnippet"
  | "language"
  | "languageGroup"
  | "resumeBubblesSection"
  | "resumeTabSection"
  | "resumeTabSubsection"
  | "timelineEvent";

export type IEntry =
  | IBlogPost
  | ICodeSnippet
  | ILanguage
  | ILanguageGroup
  | IResumeBubblesSection
  | IResumeTabSection
  | IResumeTabSubsection
  | ITimelineEvent;

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
